.github/paths-labeller.yml
It adds the descriptor that the botelastic probot needs to monitor this repo, labelling any PR modifying any file in the repo.
Less manual work :robot:
For the bot to monitor the repo, it's required that the `Elastic Employees` role has Write access to the repo
=> chore: add a bot that labels any PR with the team label

.ci/Jenkinsfile, .ci/jenkins-go-agent/Dockerfile, pkg/client/client.go, pkg/client/client_test.go, pkg/client/reader.go
Changes `New` and `NewFromReader` to return `Client` as an interface instead of a struct. This will allow others to mock the client in tests or other situations where it might be required.
=> Change pkg/client.Client to an interface

pkg/client/client.go, pkg/client/client_test.go
* Extend the Client interface with RegisterAction/UnregisterAction
* Update the signature of Execute API to pass the content, to allow cancelling with the context.Context if needed.
Needed to be able to register the actions with the gRPC client after it was created.
=> Extend the client to allow to register/unregister actions handlers

pkg/client/artifact_test.go, pkg/client/client_test.go, pkg/client/client_v2_test.go, pkg/client/log_test.go, pkg/client/mock/helpers.go, pkg/client/mock/stub_serverV1.go, pkg/client/mock/stub_serverV2.go, pkg/client/reader_test.go, pkg/client/store_test.go
This moves all of the "stub" controller servers used by the client tests to their own package, where they can be exported and used elsewhere.
I mainly wanted this for the shipper, since I needed something to test against until the V2 controller is complete.
=> Move the stub servers to an exportable package

pkg/client/client_v2.go, pkg/client/unit.go
This is a nice to have for helping with logging. Added to easily take the different types and turn them into strings. Implemented the `Stringer` interface.
=> [v2] Add stringer interface to client types.

pkg/client/client_v2.go, pkg/client/client_v2_test.go, pkg/client/diagnostics.go, pkg/client/mock/stub_serverV1.go, pkg/client/mock/stub_serverV2.go, pkg/client/unit.go
Completes the TODO for supporting the new diagnostics for the V2 protocol. With this change any component that uses the client gets all the defaults from the runtime/pprof included.
The client can have diagnostics that each unit will inherit and then each unit can define its own diagnostic as well.
Elastic Agent will call this per unit to provide all the diagnostics information for the running components unit.
=> Add ability to call diagnostics with V2 protocol and add defaults.

pkg/client/client_v2.go, pkg/client/unit.go, pkg/client/unit_test.go
First PR to fix https://github.com/elastic/elastic-agent/issues/1738 and https://github.com/elastic/apm-server/pull/9544#issuecomment-1316473137
This attempts to fix an underlying issue where V2 clients are seeing unit update events where the config has apparently remained unchanged. In order for that change event to be generated, The underlying unit needs to have an incremented config index, and a different config. I'm not sure why we're seeing an incremented index, but this at least fixes how we try to compare the structs. Instead of `!=` on two pointers, this does a `reflect.DeepEqual` on the underlying source config.
=> Change struct compare statement in unit update

pkg/client/client_v2.go
This changes the logic to always to send the observed state once a unit has been removed.
With out this change when units are removed the observed state is not sent to the Elastic Agent until the next checkin timeout which can be up to 25 seconds.
=> Always send observed after removals

pkg/client/unit.go
Fixes a panic I noticed while writing tests, we can get a nil reference if we forget to include a source field. This just uses the proper `Get*()` calls so we can avoid that.
=> Use GetSource() calls to compare structs in updateState()

pkg/client/client_v2.go, pkg/client/client_v2_test.go
Follow up to https://github.com/elastic/elastic-agent-client/pull/56.
While updating the `management.TestManagerV2` test in https://github.com/elastic/beats/pull/34456 to account for feature flags, I realized `elastic-agent-client` wasn't reporting it's current feature flag status in the observed state sent to the server (Agent) during checkin.  This PR fixes that miss.
=> Send feature flags information as part of observed state in the next checkin

pkg/client/client_v2.go, pkg/client/client_v2_test.go, pkg/client/unit.go
Add a minimum timeout to `(*clientV2).startCheckin` and `(*clientV2).startActions` so retries of `checkinRoundTrip` and `actionRoundTrip` don't spinlock if there's an RPC error (see https://github.com/elastic/elastic-agent-client/issues/66).
Fixes https://github.com/elastic/elastic-agent-client/issues/66.
fix https://github.com/elastic/elastic-agent/issues/2628
At the same time, break some monolithic functions up into multiple helpers, fix some race conditions, simplify the synchronization variables, and add explanatory comments for many steps of the checkin process.
=> Fix RPC error spinlock / clean up clientV2

pkg/client/mock/stub_serverV2.go
Allow to set a port to `StubServerV2`. If its `Port` field is set, this is the port used to open the TCP listener, if no port is set a random one will be used. In all cases after `Start` is called, the `Port` field will contain the port the server is listening on.
Closes https://github.com/elastic/elastic-agent-client/issues/42
=> Allow to set a port for the V2 stub server

go.mod
What the title says. Only change is the minor version in the go.mod file.
=> Upgrade to go 1.21.

pkg/client/mock/stub_serverV2.go
Instead of the unspecified IP address use the `Addr()` from [`Listener`](https://pkg.go.dev/net#Listener) to set the value of target.
=> stub server v2: set target from listener

pkg/client/unit.go, pkg/client/unit_test.go
This PR adds checks for the RevisionNumber and Streams of the UnitExpectedConfig to properly cause a `TriggeredConfigChange`. 
@blakerouse I think you are the original implementor of the new control protocol, so any thoughts on that?
=> [Unit/Change]: trigger config change on unit config and revision changes

magefile.go
As explained by @fearful-symmetry in https://github.com/elastic/elastic-agent-client/pull/110#issuecomment-2129967660:
> the `go get` operation we're using breaks on 1.22:
> ```
> mage prepare:all                                                                                                                                                
> go: modules disabled by GO111MODULE=off; see 'go help modules'
> Error: running "go get github.com/elastic/go-licenser" failed with exit code 1
> ```
> 
> I'm guessing the original code did this since it was a bit of a hack to install binaries without using `go install` However, this > doesn't work in go 1.22 anymore:
> https://tip.golang.org/doc/go1.22
> 
>> go get is no longer supported outside of a module in the legacy GOPATH mode (that is, with …
=> Replace go get usage

pkg/client/client_v2.go, pkg/client/client_v2_test.go, pkg/client/reader.go
So, its been a while since I've tinkered with the agent client stuff, so when I did https://github.com/elastic/elastic-agent-client/pull/110 I forgot that I _also_ needed to change all the client helpers, and not just the GRPC. This also updates the client go code.
=> Add management mode to client-side AgentInfo structs

pkg/client/mock/npipe_windows.go
https://github.com/elastic/elastic-agent-client/pull/91 introduced `newNPipeListener` but didn't add the import.
- I think it wants to use the `github.com/elastic/elastic-agent-libs/api/npipe` library. Correct me if I'm wrong @blakerouse / @aleksmaus
This PR adds the missing import.
=> [npipe][fix] add a missing npipe import for windows

pkg/client/reader.go, pkg/client/store_test.go, pkg/client/unit_test.go
Minor code adjustments to fix static code analysis issues.
=> Fix static code analysis issues

go.mod
What it says on the tin.  Just a change in `go.mod`.
=> Upgrading go version to 1.23
